# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commander',
            options={'ordering': ('-created',)},
        ),
        migrations.AddField(
            model_name='commander',
            name='api_token',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='commander',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
