# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 00:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cmdrs', '0003_add_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commander',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commanders', to=settings.AUTH_USER_MODEL),
        ),
    ]
