# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[(b'zerogravity', b'Zero Gravity'), (b'surface', b'Surface'), (b'srvrally', b'SRV Rally'), (b'srvcross', b'SRV Cross'), (b'stadium', b'Stadium')], db_index=True, max_length=16),
        ),
        migrations.AlterField(
            model_name='course',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='course',
            name='system',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='coursescreenshot',
            name='created',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='coursescreenshot',
            name='is_primary',
            field=models.BooleanField(db_index=True, default=False, help_text=b'Is this the main/best image the user should see?'),
        ),
        migrations.AlterField(
            model_name='srvcrosscourse',
            name='planet_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='srvcrosscourse',
            name='port_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='srvcrosscourse',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[(b'ship', b'Ship'), (b'srv', b'SRV')], db_index=True, default=b'ship', max_length=8),
        ),
        migrations.AlterField(
            model_name='srvrallycourse',
            name='planet_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='srvrallycourse',
            name='planet_type',
            field=models.CharField(choices=[(b'rock', b'rock'), (b'ice', b'ice'), (b'lava', b'lava'), (b'metallic', b'metallic'), (b'water', b'water'), (b'earth-like', b'earth-like'), (b'ammonia', b'ammonia'), (b'gas', b'gas')], db_index=True, default=b'rock', max_length=32),
        ),
        migrations.AlterField(
            model_name='srvrallycourse',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[(b'ship', b'Ship'), (b'srv', b'SRV')], db_index=True, default=b'ship', max_length=8),
        ),
        migrations.AlterField(
            model_name='stadiumcourse',
            name='planet_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stadiumcourse',
            name='port_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stadiumcourse',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[(b'ship', b'Ship'), (b'srv', b'SRV')], db_index=True, default=b'ship', max_length=8),
        ),
        migrations.AlterField(
            model_name='surfacecourse',
            name='planet_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='surfacecourse',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[(b'ship', b'Ship'), (b'srv', b'SRV')], db_index=True, default=b'ship', max_length=8),
        ),
        migrations.AlterField(
            model_name='zerogravitycourse',
            name='station_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='zerogravitycourse',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[(b'ship', b'Ship'), (b'srv', b'SRV')], db_index=True, default=b'ship', max_length=8),
        ),
    ]
