# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_approve_existing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='srvcrosscourse',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[(b'ship', b'Ship'), (b'srv', b'SRV')], db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='srvrallycourse',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[(b'ship', b'Ship'), (b'srv', b'SRV')], db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='stadiumcourse',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[(b'ship', b'Ship'), (b'srv', b'SRV')], db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='surfacecourse',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[(b'ship', b'Ship'), (b'srv', b'SRV')], db_index=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='zerogravitycourse',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[(b'ship', b'Ship'), (b'srv', b'SRV')], db_index=True, max_length=8),
        ),
    ]
