# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-01 20:20
from __future__ import unicode_literals

import courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_vehicle_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursescreenshot',
            name='shot',
            field=models.ImageField(max_length=255, upload_to=courses.models.screenshot_location),
        ),
    ]
